applicationApiVersion: v1beta1

properties:
  APP_INSTANCE_NAME:
    type: string
    x-google-marketplace:
      type: NAME

  NAMESPACE:
    type: string
    x-google-marketplace:
      type: NAMESPACE

  AGONES_CONTROLLER_IMAGE:
    type: string
    default: $REGISTRY:$TAG
    x-google-marketplace:
      type: IMAGE
      image:
        generatedProperties:
          splitToRegistryRepoTag:
            registry: agones.agones.image.registry
            repo: agones.agones.image.controller.name
            tag: agones.agones.image.tag

  AGONES_SDK_IMAGE:
    type: string
    default: $REGISTRY/agones-sdk:$TAG
    x-google-marketplace:
      type: IMAGE
      image:
        generatedProperties:
          splitToRegistryRepoTag:
            registry: agones.agones.image.registry
            repo: agones.agones.image.sdk.name
            tag: agones.agones.image.tag

  AGONES_PING_IMAGE:
    type: string
    default: $REGISTRY/agones-ping:$TAG
    x-google-marketplace:
      type: IMAGE
      image:
        generatedProperties:
          splitToRegistryRepoTag:
            registry: agones.agones.image.registry
            repo: agones.agones.image.ping.name
            tag: agones.agones.image.tag

  agones.agones.serviceaccount.controller:
    type: string
    title: Service account used by Agones main controller.
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        roles:
        - type: ClusterRole
          rulesType: CUSTOM
          rules:
          - apiGroups: [""]
            resources: ["events"]
            verbs: ["create", "patch"]
          - apiGroups: [""]
            resources: ["pods"]
            verbs: ["create", "delete", "list", "watch"]
          - apiGroups: [""]
            resources: ["nodes"]
            verbs: ["list", "watch"]
          - apiGroups: ["apiextensions.k8s.io"]
            resources: ["customresourcedefinitions"]
            verbs: ["get"]
          - apiGroups: ["stable.agones.dev"]
            resources: ["gameservers", "gameserversets"]
            verbs: ["create", "delete", "get", "list", "update", "watch"]
          - apiGroups: ["stable.agones.dev"]
            resources: ["gameservers"]
            verbs: ["patch"]
          - apiGroups: ["stable.agones.dev"]
            resources: ["fleets", "fleetallocations", "fleetautoscalers"]
            verbs: ["get", "list", "update", "watch"]
          - apiGroups: ["stable.agones.dev"]
            resources: ["gameserverallocations"]
            verbs: ["list", "watch",  "delete"]

  agones.agones.serviceaccount.sdk:
    type: string
    title: Service account used by Agones sdk controller.
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        roles:
        - type: ClusterRole
          rulesType: CUSTOM
          rules:
          - apiGroups: [""]
            resources: ["events"]
            verbs: ["create"]
          - apiGroups: ["stable.agones.dev"]
            resources: ["gameservers"]
            verbs: ["list", "update", "watch"]

  INSTALL_XONOTIC_DEMO:
    type: boolean
    title: By selecting this, a Xonotic (sample opensource game) fleet will be registered and automatically installed into the cluster.
    default: false

  marketplace_integration.service_account:
    type: string
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        roles:
        - type: ClusterRole
          rulesType: PREDEFINED
          rulesFromRoleName: cluster-admin

  marketplace_integration.image:
    type: string
    x-google-marketplace:
      type: DEPLOYER_IMAGE


required:
- APP_INSTANCE_NAME
- NAMESPACE
- AGONES_CONTROLLER_IMAGE
- AGONES_SDK_IMAGE
- AGONES_PING_IMAGE
- INSTALL_XONOTIC_DEMO
